### ISSUE TITLE
ClassificationEvaluator fails because of missing "task" parameter.

### ISSUE THREAD

**Issue by x-tabdeveloping** [KennethEnevoldsen/scandinavian-embedding-benchmark#72]
I'm trying to test the FastText models that I wrote an implementation for, and I get this error:
```
INFO:seb.cli.run:Model registered in SEB. Loading from registry.
Running fasttext-cc-nb-300:   0%|                                                                                                        | 0/1 [00:00<?, ?it/sINFO:mteb.abstasks.AbsTaskClassification:%|                                                                                               | 0/6 [00:00<?, ?it/s]
Task: ScalaDaClassification, split: test. Running...
INFO:mteb.abstasks.AbsTaskClassification:========== Experiment 1/10 ==========
INFO:mteb.evaluation.evaluators.ClassificationEvaluator:Encoding 32 training sentences...
Running fasttext-cc-nb-300:   0%|                                                                                                        | 0/1 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "/home/au689890/anaconda3/envs/seb/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/au689890/anaconda3/envs/seb/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/au689890/Documents/Github/scandinavian-embedding-benchmark/src/seb/__main__.py", line 4, in <module>
    setup_cli()
  File "/home/au689890/Documents/Github/scandinavian-embedding-benchmark/src/seb/cli/cli.py", line 9, in setup_cli
    cli.run()
  File "/home/au689890/anaconda3/envs/seb/lib/python3.9/site-packages/radicli/cli.py", line 296, in run
    func(**values)
  File "/home/au689890/Documents/Github/scandinavian-embedding-benchmark/src/seb/cli/run.py", line 138, in run_benchmark_cli
    benchmark_results = benchmark.evaluate_models(
  File "/home/au689890/Documents/Github/scandinavian-embedding-benchmark/src/seb/benchmark.py", line 211, in evaluate_models
    self.evaluate_model(
  File "/home/au689890/Documents/Github/scandinavian-embedding-benchmark/src/seb/benchmark.py", line 172, in evaluate_model
    task_result = run_task(
  File "/home/au689890/Documents/Github/scandinavian-embedding-benchmark/src/seb/benchmark.py", line 90, in run_task
    task_result = task.evaluate(model)
  File "/home/au689890/Documents/Github/scandinavian-embedding-benchmark/src/seb/registered_tasks/multilingual.py", line 101, in evaluate
    score = mteb_task.evaluate(model)
  File "/home/au689890/anaconda3/envs/seb/lib/python3.9/site-packages/mteb/abstasks/AbsTaskClassification.py", line 55, in evaluate
    scores = self._evaluate_monolingual(model, self.dataset, eval_split, train_split, **kwargs)
  File "/home/au689890/anaconda3/envs/seb/lib/python3.9/site-packages/mteb/abstasks/AbsTaskClassification.py", line 90, in _evaluate_monolingual
    scores_exp, test_cache = evaluator(model, test_cache=test_cache)
  File "/home/au689890/anaconda3/envs/seb/lib/python3.9/site-packages/mteb/evaluation/evaluators/ClassificationEvaluator.py", line 211, in __call__
    X_train = np.asarray(model.encode(self.sentences_train, batch_size=self.batch_size))
TypeError: encode() missing 1 required keyword-only argument: 'task'```
Apparently ClassificationEvaluator does not by default pass a task argument to `EmbeddingModel`, which requires it.
I literally copied the implementation of Cohere embeddings and started from there and with the old API, the FastText models worked just fine.
Just for completeness's sake here's my implementation, it's very barebones, nothing fancy, I don't see why it should break the pipeline:
```python
class FastTextModel(seb.Encoder):
    def __init__(self, model_name: str, lang: str) -> None:
        self.model_name = model_name
        self.lang = lang

    def get_embedding_dim(self) -> int:
        import fasttext
        import fasttext.util

        fasttext.util.download_model(self.lang, if_exists="ignore")
        model = fasttext.load_model(self.model_name)
        return model.get_dimension()

    def encode(
        self,
        sentences: list[str],
        **kwargs: Any,
    ) -> torch.Tensor:
        # Things happen here
        ...
        return torch.tensor(np.stack(embeddings))

# I'm only including one model here, but I have one for each language
@models.register("fasttext-cc-da-300")
def create_cc_da_300() -> seb.EmbeddingModel:
    model_name = "fasttext-cc-da-300"
    meta = seb.ModelMeta(
        name=model_name,
        huggingface_name=None,
        reference="https://fasttext.cc/docs/en/crawl-vectors.html",
        languages=["da"],
        open_source=True,
        embedding_size=300,
    )
    return seb.EmbeddingModel(
        loader=partial(FastTextModel, model_name="cc.da.300.bin", lang="da"),
        meta=meta,
    )

```
Do we know where this issue might originate from?

**Comment by KennethEnevoldsen** [comment]
Hmm that should happen here:

https://github.com/KennethEnevoldsen/scandinavian-embedding-benchmark/blob/b030aefcb83742ea85d33000acbe6675e02162c4/src/seb/interfaces/mteb_task.py#L79

Where the model is wrapped like this:
https://github.com/KennethEnevoldsen/scandinavian-embedding-benchmark/blob/b030aefcb83742ea85d33000acbe6675e02162c4/src/seb/interfaces/mteb_task.py#L15-L21

**Comment by KennethEnevoldsen** [comment]
but it does not seem like your model takes a task KW-only argument?

**Comment by KennethEnevoldsen** [comment]
Ahh it is a bug in the scala dataset!
